spring:
  profiles:
    active: mysql
---
###################
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true # H2 콘솔 활성화
      path: /h2-console # 접속 경로
  # H2는 자동으로 설정되므로 datasource 정보는 생략해도 잘 동작함
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
  batch:
    jdbc:
      initialize-schema: embedded
##    job:
      # 여기에 실행할 Job의 Bean 이름을 적어줍니다.
##      name: job

---
###################
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: never
##    job:
      # 여기에 실행할 Job의 Bean 이름을 적어줍니다.
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
##      name: job


logging:
  level:
    # 스프링 프레임워크의 웹 관련 로그를 DEBUG로 설정
    org.springframework.web: DEBUG

    # Hibernate(JPA)가 실행하는 SQL 쿼리를 보고 싶을 때
    org.hibernate.SQL: DEBUG

    # SQL 바인딩 파라미터(?, ?)까지 상세하게 보고 싶을 때
    org.hibernate.type.descriptor.sql: TRACE